### ISSUE TITLE
"types-regex" is missing

### ISSUE THREAD

**Issue by AIGeneratedUsername** [asottile/types-all#16]
Sorry for probably stupid question, but why some stubs are missing, e.g. [`types-regex`](https://github.com/python/typeshed/tree/master/stubs/regex)? 

Is the only reason is that the "types-all" did not parse stubs for a very long time?

**Comment by asottile** [comment]
this is a shim for the typeshed changes. as such it is a snapshot of what was in typeshed when that changed and nothing more

types-regex was not in typeshed
